### ISSUE TITLE
WHY DOES IT KEEP SHITTING

### ISSUE THREAD

**Issue by mixcoac** [SlippingGitty/discord-token-shitter#2]
PLEASE HELP IT SHITS AND SHITS AND SHITS AND SHITS AND SHITS AND SHITS AND SHITS AND SHITS AND SHITS AND SHITS AND SHITS AND SHITS AND SHITS AND SHITS AND SHITS AND SHITS AND SHITS AND SHITS AND SHITS AND SHITS AND SHITS AND SHITS AND SHITS AND SHITS AND SHITS AND SHITS AND SHITS AND SHITS AND SHITS AND SHITS AND SHITS AND SHITS AND SHITS AND SHITS AND SHITS AND SHITS AND SHITS

**Comment by Loremly** [comment]
HAS IT STOPPED SHITTING?!

**Comment by mixcoac** [comment]
NO, I WENT TO SLEEP AND THE DAMN THING MADE MY HOUSE FUCKING BURN. IT JUST SHITTED TILL MY HOUSE WAS ON FIRE

**Comment by Loremly** [comment]
HOW DOES SHIT PRODUCE FIRE?!

**Comment by SlippingGitty** [comment]
> HOW DOES SHIT PRODUCE FIRE?!

eminem puts out an occasional goodie

**Comment by mixcoac** [comment]
I AM CONSIDERING ON TAKING @SlippingGitty TO COURT FOR MAKING SUCH AN HORRENDOUS PROGRAM THAT ALMOST BURNED MY HOUSE DOWN

**Comment by SlippingGitty** [comment]
phew alright well, let me ask dperolio if i can borrow his lawyers and see if they're willing to take the case pro bono

**Comment by Loremly** [comment]
> I AM CONSIDERING ON TAKING @SlippingGitty TO COURT FOR MAKING SUCH AN HORRENDOUS PROGRAM THAT ALMOST BURNED MY HOUSE DOWN

YES SUE THEM! FOR DISTURBING THE PEACEFUL, ENDANGERMENT, ATTEMPTED MURDER, AND UH UHM UHM... VANDALIZING!!!
